version: "3.5"

networks:
  hydra-net:
    external: true

volumes:
  hydra-data:
    external: true

services:
  hydra:
    container_name: hydra
    image: oryd/hydra:v1.2.3
    networks:
      - hydra-net
    ports:
      - "9000:4444"
      - "9001:4445"
    environment:
      - URLS_SELF_ISSUER
      - SECRETS_SYSTEM
      - "DSN=postgres://hydra_user:${POSTGRES_PASSWORD}@hydra-db:5432/hydra_db?sslmode=disable"
      - "URLS_LOGIN=${ODP_IDENTITY_URL}/hydra/login"
      - "URLS_CONSENT=${ODP_IDENTITY_URL}/hydra/consent"
      - "URLS_LOGOUT=${ODP_IDENTITY_URL}/hydra/logout"

      # TODO remove; the following makes access token lifetime 1 week (the default is 1 hour),
      # as a workaround until such time as we've implemented token refresh on the client side
      - TTL_ACCESS_TOKEN=168h
    depends_on:
      - hydra-db
    restart: always

  hydra-db:
    container_name: hydra-db
    image: postgres:9.6
    networks:
      - hydra-net
    volumes:
      - hydra-data:/var/lib/postgresql/data
    environment:
      - PGDATA=/var/lib/postgresql/data
      - POSTGRES_DB=hydra_db
      - POSTGRES_USER=hydra_user
      - POSTGRES_PASSWORD
    restart: always
